apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    env: demo
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: demo
      tier: frontend
  template:
    metadata:
      name: nginx-pod-yaml
      labels:
        env: demo
        tier: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always