apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: worker-app
    type: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker-app
      type: backend
  template:
    metadata: 
      name: worker-app-pod
      labels:
         app: worker-app
         type: backend
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_worker:v1
